version: "3.8"
services:
  accounts-db:
    image: postgres
    restart: always
    volumes:
       - flow-storage-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flow-dev
      - "POSTGRES_USER=${DEV_DB_USER}"
      - "POSTGRES_PASSWORD=${DEV_DB_PWD}"
    ports:
      - "${DEV_DB_PORT}:5432"
       
volumes:
  flow-storage-data: