name: .NET build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src

  plugins:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Build plugin dependencies
      shell: pwsh
      run: |
        ./flow.plugin-deps.ps1
      working-directory: ./build/_scripts
    - name: "[Transfer detection plugin] restore"
      run: dotnet restore --configfile Nuget.Config
      working-directory: ./src/plugins/transactions/Flow.Plugins.Transactions.TKF
    - name: "[Transfer detection plugin] build"
      run: dotnet build --no-restore
      working-directory: ./src/plugins/transactions/Flow.Plugins.Transactions.TKF
